/* tslint:disable */
/* eslint-disable */
//  This file was automatically generated and should not be edited.

export type CreatePendingInput = {
  id?: string | null,
  purchaseOrder?: boolean | null,
  survey?: boolean | null,
  drawingsApproved?: boolean | null,
  drawings?: boolean | null,
  completed?: boolean | null,
  depositPaid?: boolean | null,
  orderPlaced?: boolean | null,
  shippingDetails?: boolean | null,
  invoices?: boolean | null,
  quotationDetails?: boolean | null,
  _version?: number | null,
};

export type ModelPendingConditionInput = {
  purchaseOrder?: ModelBooleanInput | null,
  survey?: ModelBooleanInput | null,
  drawingsApproved?: ModelBooleanInput | null,
  drawings?: ModelBooleanInput | null,
  completed?: ModelBooleanInput | null,
  depositPaid?: ModelBooleanInput | null,
  orderPlaced?: ModelBooleanInput | null,
  shippingDetails?: ModelBooleanInput | null,
  invoices?: ModelBooleanInput | null,
  quotationDetails?: ModelBooleanInput | null,
  and?: Array< ModelPendingConditionInput | null > | null,
  or?: Array< ModelPendingConditionInput | null > | null,
  not?: ModelPendingConditionInput | null,
};

export type ModelBooleanInput = {
  ne?: boolean | null,
  eq?: boolean | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
};

export enum ModelAttributeTypes {
  binary = "binary",
  binarySet = "binarySet",
  bool = "bool",
  list = "list",
  map = "map",
  number = "number",
  numberSet = "numberSet",
  string = "string",
  stringSet = "stringSet",
  _null = "_null",
}


export type Pending = {
  __typename: "Pending",
  id: string,
  purchaseOrder?: boolean | null,
  survey?: boolean | null,
  drawingsApproved?: boolean | null,
  drawings?: boolean | null,
  completed?: boolean | null,
  depositPaid?: boolean | null,
  orderPlaced?: boolean | null,
  shippingDetails?: boolean | null,
  invoices?: boolean | null,
  quotationDetails?: boolean | null,
  createdAt: string,
  updatedAt: string,
  _version: number,
  _deleted?: boolean | null,
  _lastChangedAt: number,
};

export type UpdatePendingInput = {
  id: string,
  purchaseOrder?: boolean | null,
  survey?: boolean | null,
  drawingsApproved?: boolean | null,
  drawings?: boolean | null,
  completed?: boolean | null,
  depositPaid?: boolean | null,
  orderPlaced?: boolean | null,
  shippingDetails?: boolean | null,
  invoices?: boolean | null,
  quotationDetails?: boolean | null,
  _version?: number | null,
};

export type DeletePendingInput = {
  id: string,
  _version?: number | null,
};

export type CreateOrderInfInput = {
  id?: string | null,
  itemName?: string | null,
  itemQuantity?: number | null,
  width?: number | null,
  drop?: number | null,
  cost?: number | null,
  ordersID: string,
  reference?: string | null,
  production?: boolean | null,
  extras?: Array< string | null > | null,
  productionSpecification?: string | null,
  _version?: number | null,
};

export type ModelOrderInfConditionInput = {
  itemName?: ModelStringInput | null,
  itemQuantity?: ModelIntInput | null,
  width?: ModelIntInput | null,
  drop?: ModelIntInput | null,
  cost?: ModelFloatInput | null,
  ordersID?: ModelIDInput | null,
  reference?: ModelStringInput | null,
  production?: ModelBooleanInput | null,
  extras?: ModelStringInput | null,
  productionSpecification?: ModelStringInput | null,
  and?: Array< ModelOrderInfConditionInput | null > | null,
  or?: Array< ModelOrderInfConditionInput | null > | null,
  not?: ModelOrderInfConditionInput | null,
};

export type ModelStringInput = {
  ne?: string | null,
  eq?: string | null,
  le?: string | null,
  lt?: string | null,
  ge?: string | null,
  gt?: string | null,
  contains?: string | null,
  notContains?: string | null,
  between?: Array< string | null > | null,
  beginsWith?: string | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
  size?: ModelSizeInput | null,
};

export type ModelSizeInput = {
  ne?: number | null,
  eq?: number | null,
  le?: number | null,
  lt?: number | null,
  ge?: number | null,
  gt?: number | null,
  between?: Array< number | null > | null,
};

export type ModelIntInput = {
  ne?: number | null,
  eq?: number | null,
  le?: number | null,
  lt?: number | null,
  ge?: number | null,
  gt?: number | null,
  between?: Array< number | null > | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
};

export type ModelFloatInput = {
  ne?: number | null,
  eq?: number | null,
  le?: number | null,
  lt?: number | null,
  ge?: number | null,
  gt?: number | null,
  between?: Array< number | null > | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
};

export type ModelIDInput = {
  ne?: string | null,
  eq?: string | null,
  le?: string | null,
  lt?: string | null,
  ge?: string | null,
  gt?: string | null,
  contains?: string | null,
  notContains?: string | null,
  between?: Array< string | null > | null,
  beginsWith?: string | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
  size?: ModelSizeInput | null,
};

export type OrderInf = {
  __typename: "OrderInf",
  id: string,
  itemName?: string | null,
  itemQuantity?: number | null,
  width?: number | null,
  drop?: number | null,
  cost?: number | null,
  ordersID: string,
  reference?: string | null,
  production?: boolean | null,
  extras?: Array< string | null > | null,
  productionSpecification?: string | null,
  createdAt: string,
  updatedAt: string,
  _version: number,
  _deleted?: boolean | null,
  _lastChangedAt: number,
};

export type UpdateOrderInfInput = {
  id: string,
  itemName?: string | null,
  itemQuantity?: number | null,
  width?: number | null,
  drop?: number | null,
  cost?: number | null,
  ordersID?: string | null,
  reference?: string | null,
  production?: boolean | null,
  extras?: Array< string | null > | null,
  productionSpecification?: string | null,
  _version?: number | null,
};

export type DeleteOrderInfInput = {
  id: string,
  _version?: number | null,
};

export type CreateOrdersInput = {
  id?: string | null,
  orderDate?: string | null,
  quotationNo?: string | null,
  projectName?: string | null,
  projectReference?: string | null,
  siteContactManager?: string | null,
  siteContactSupervisor?: string | null,
  status?: Status | null,
  orderValue?: number | null,
  siteAddress?: string | null,
  customersID: string,
  lastUpdatedBy: string,
  sfclTerms?: string | null,
  sfclCreditScore?: string | null,
  sfclRecommended?: string | null,
  sfclInsured?: boolean | null,
  supply?: string | null,
  customerCollection?: boolean | null,
  deliveryCharge?: string | null,
  estimatedCollectionDelivery?: string | null,
  estimateProjectCompletion?: string | null,
  sfclDelivered?: string | null,
  siteContactManagerNumber?: string | null,
  siteContactSupervisorNumber?: string | null,
  siteWorkingHours?: string | null,
  _version?: number | null,
  ordersPendingId?: string | null,
};

export enum Status {
  PENDING = "PENDING",
  PRODUCTION_READY = "PRODUCTION_READY",
  BOOKING = "BOOKING",
  INSTALLATION = "INSTALLATION",
  INVOICE = "INVOICE",
  PRODUCTION_SPECIFICATION = "PRODUCTION_SPECIFICATION",
}


export type ModelOrdersConditionInput = {
  orderDate?: ModelStringInput | null,
  quotationNo?: ModelStringInput | null,
  projectName?: ModelStringInput | null,
  projectReference?: ModelStringInput | null,
  siteContactManager?: ModelStringInput | null,
  siteContactSupervisor?: ModelStringInput | null,
  status?: ModelStatusInput | null,
  orderValue?: ModelFloatInput | null,
  siteAddress?: ModelStringInput | null,
  customersID?: ModelIDInput | null,
  lastUpdatedBy?: ModelStringInput | null,
  sfclTerms?: ModelStringInput | null,
  sfclCreditScore?: ModelStringInput | null,
  sfclRecommended?: ModelStringInput | null,
  sfclInsured?: ModelBooleanInput | null,
  supply?: ModelStringInput | null,
  customerCollection?: ModelBooleanInput | null,
  deliveryCharge?: ModelStringInput | null,
  estimatedCollectionDelivery?: ModelStringInput | null,
  estimateProjectCompletion?: ModelStringInput | null,
  sfclDelivered?: ModelStringInput | null,
  siteContactManagerNumber?: ModelStringInput | null,
  siteContactSupervisorNumber?: ModelStringInput | null,
  siteWorkingHours?: ModelStringInput | null,
  and?: Array< ModelOrdersConditionInput | null > | null,
  or?: Array< ModelOrdersConditionInput | null > | null,
  not?: ModelOrdersConditionInput | null,
  ordersPendingId?: ModelIDInput | null,
};

export type ModelStatusInput = {
  eq?: Status | null,
  ne?: Status | null,
};

export type Orders = {
  __typename: "Orders",
  id: string,
  orderDate?: string | null,
  quotationNo?: string | null,
  projectName?: string | null,
  projectReference?: string | null,
  siteContactManager?: string | null,
  siteContactSupervisor?: string | null,
  status?: Status | null,
  orderValue?: number | null,
  siteAddress?: string | null,
  customersID: string,
  OrderInfs?: ModelOrderInfConnection | null,
  lastUpdatedBy: string,
  Pending?: Pending | null,
  sfclTerms?: string | null,
  sfclCreditScore?: string | null,
  sfclRecommended?: string | null,
  sfclInsured?: boolean | null,
  supply?: string | null,
  customerCollection?: boolean | null,
  deliveryCharge?: string | null,
  estimatedCollectionDelivery?: string | null,
  estimateProjectCompletion?: string | null,
  sfclDelivered?: string | null,
  siteContactManagerNumber?: string | null,
  siteContactSupervisorNumber?: string | null,
  siteWorkingHours?: string | null,
  createdAt: string,
  updatedAt: string,
  _version: number,
  _deleted?: boolean | null,
  _lastChangedAt: number,
  ordersPendingId?: string | null,
};

export type ModelOrderInfConnection = {
  __typename: "ModelOrderInfConnection",
  items:  Array<OrderInf | null >,
  nextToken?: string | null,
  startedAt?: number | null,
};

export type UpdateOrdersInput = {
  id: string,
  orderDate?: string | null,
  quotationNo?: string | null,
  projectName?: string | null,
  projectReference?: string | null,
  siteContactManager?: string | null,
  siteContactSupervisor?: string | null,
  status?: Status | null,
  orderValue?: number | null,
  siteAddress?: string | null,
  customersID?: string | null,
  lastUpdatedBy?: string | null,
  sfclTerms?: string | null,
  sfclCreditScore?: string | null,
  sfclRecommended?: string | null,
  sfclInsured?: boolean | null,
  supply?: string | null,
  customerCollection?: boolean | null,
  deliveryCharge?: string | null,
  estimatedCollectionDelivery?: string | null,
  estimateProjectCompletion?: string | null,
  sfclDelivered?: string | null,
  siteContactManagerNumber?: string | null,
  siteContactSupervisorNumber?: string | null,
  siteWorkingHours?: string | null,
  _version?: number | null,
  ordersPendingId?: string | null,
};

export type DeleteOrdersInput = {
  id: string,
  _version?: number | null,
};

export type CreateCustomersInput = {
  id?: string | null,
  customer: string,
  businessName?: string | null,
  email?: string | null,
  contactNum?: string | null,
  accountsContact?: string | null,
  regNumber?: string | null,
  trustedPayer?: boolean | null,
  creditLimit?: number | null,
  billingAddress?: string | null,
  accountsEmail?: string | null,
  vatNumber?: string | null,
  taxReference?: string | null,
  vatExempt?: boolean | null,
  vatReverse?: boolean | null,
  cisDeductions?: boolean | null,
  cisName?: string | null,
  cisRate?: string | null,
  cisOrgType?: string | null,
  _version?: number | null,
};

export type ModelCustomersConditionInput = {
  customer?: ModelStringInput | null,
  businessName?: ModelStringInput | null,
  email?: ModelStringInput | null,
  contactNum?: ModelStringInput | null,
  accountsContact?: ModelStringInput | null,
  regNumber?: ModelStringInput | null,
  trustedPayer?: ModelBooleanInput | null,
  creditLimit?: ModelIntInput | null,
  billingAddress?: ModelStringInput | null,
  accountsEmail?: ModelStringInput | null,
  vatNumber?: ModelStringInput | null,
  taxReference?: ModelStringInput | null,
  vatExempt?: ModelBooleanInput | null,
  vatReverse?: ModelBooleanInput | null,
  cisDeductions?: ModelBooleanInput | null,
  cisName?: ModelStringInput | null,
  cisRate?: ModelStringInput | null,
  cisOrgType?: ModelStringInput | null,
  and?: Array< ModelCustomersConditionInput | null > | null,
  or?: Array< ModelCustomersConditionInput | null > | null,
  not?: ModelCustomersConditionInput | null,
};

export type Customers = {
  __typename: "Customers",
  id: string,
  customer: string,
  businessName?: string | null,
  email?: string | null,
  contactNum?: string | null,
  accountsContact?: string | null,
  regNumber?: string | null,
  trustedPayer?: boolean | null,
  creditLimit?: number | null,
  Orders?: ModelOrdersConnection | null,
  billingAddress?: string | null,
  accountsEmail?: string | null,
  vatNumber?: string | null,
  taxReference?: string | null,
  vatExempt?: boolean | null,
  vatReverse?: boolean | null,
  cisDeductions?: boolean | null,
  cisName?: string | null,
  cisRate?: string | null,
  cisOrgType?: string | null,
  createdAt: string,
  updatedAt: string,
  _version: number,
  _deleted?: boolean | null,
  _lastChangedAt: number,
};

export type ModelOrdersConnection = {
  __typename: "ModelOrdersConnection",
  items:  Array<Orders | null >,
  nextToken?: string | null,
  startedAt?: number | null,
};

export type UpdateCustomersInput = {
  id: string,
  customer?: string | null,
  businessName?: string | null,
  email?: string | null,
  contactNum?: string | null,
  accountsContact?: string | null,
  regNumber?: string | null,
  trustedPayer?: boolean | null,
  creditLimit?: number | null,
  billingAddress?: string | null,
  accountsEmail?: string | null,
  vatNumber?: string | null,
  taxReference?: string | null,
  vatExempt?: boolean | null,
  vatReverse?: boolean | null,
  cisDeductions?: boolean | null,
  cisName?: string | null,
  cisRate?: string | null,
  cisOrgType?: string | null,
  _version?: number | null,
};

export type DeleteCustomersInput = {
  id: string,
  _version?: number | null,
};

export type ModelPendingFilterInput = {
  id?: ModelIDInput | null,
  purchaseOrder?: ModelBooleanInput | null,
  survey?: ModelBooleanInput | null,
  drawingsApproved?: ModelBooleanInput | null,
  drawings?: ModelBooleanInput | null,
  completed?: ModelBooleanInput | null,
  depositPaid?: ModelBooleanInput | null,
  orderPlaced?: ModelBooleanInput | null,
  shippingDetails?: ModelBooleanInput | null,
  invoices?: ModelBooleanInput | null,
  quotationDetails?: ModelBooleanInput | null,
  and?: Array< ModelPendingFilterInput | null > | null,
  or?: Array< ModelPendingFilterInput | null > | null,
  not?: ModelPendingFilterInput | null,
};

export type ModelPendingConnection = {
  __typename: "ModelPendingConnection",
  items:  Array<Pending | null >,
  nextToken?: string | null,
  startedAt?: number | null,
};

export type ModelOrderInfFilterInput = {
  id?: ModelIDInput | null,
  itemName?: ModelStringInput | null,
  itemQuantity?: ModelIntInput | null,
  width?: ModelIntInput | null,
  drop?: ModelIntInput | null,
  cost?: ModelFloatInput | null,
  ordersID?: ModelIDInput | null,
  reference?: ModelStringInput | null,
  production?: ModelBooleanInput | null,
  extras?: ModelStringInput | null,
  productionSpecification?: ModelStringInput | null,
  and?: Array< ModelOrderInfFilterInput | null > | null,
  or?: Array< ModelOrderInfFilterInput | null > | null,
  not?: ModelOrderInfFilterInput | null,
};

export enum ModelSortDirection {
  ASC = "ASC",
  DESC = "DESC",
}


export type ModelOrdersFilterInput = {
  id?: ModelIDInput | null,
  orderDate?: ModelStringInput | null,
  quotationNo?: ModelStringInput | null,
  projectName?: ModelStringInput | null,
  projectReference?: ModelStringInput | null,
  siteContactManager?: ModelStringInput | null,
  siteContactSupervisor?: ModelStringInput | null,
  status?: ModelStatusInput | null,
  orderValue?: ModelFloatInput | null,
  siteAddress?: ModelStringInput | null,
  customersID?: ModelIDInput | null,
  lastUpdatedBy?: ModelStringInput | null,
  sfclTerms?: ModelStringInput | null,
  sfclCreditScore?: ModelStringInput | null,
  sfclRecommended?: ModelStringInput | null,
  sfclInsured?: ModelBooleanInput | null,
  supply?: ModelStringInput | null,
  customerCollection?: ModelBooleanInput | null,
  deliveryCharge?: ModelStringInput | null,
  estimatedCollectionDelivery?: ModelStringInput | null,
  estimateProjectCompletion?: ModelStringInput | null,
  sfclDelivered?: ModelStringInput | null,
  siteContactManagerNumber?: ModelStringInput | null,
  siteContactSupervisorNumber?: ModelStringInput | null,
  siteWorkingHours?: ModelStringInput | null,
  and?: Array< ModelOrdersFilterInput | null > | null,
  or?: Array< ModelOrdersFilterInput | null > | null,
  not?: ModelOrdersFilterInput | null,
  ordersPendingId?: ModelIDInput | null,
};

export type ModelCustomersFilterInput = {
  id?: ModelIDInput | null,
  customer?: ModelStringInput | null,
  businessName?: ModelStringInput | null,
  email?: ModelStringInput | null,
  contactNum?: ModelStringInput | null,
  accountsContact?: ModelStringInput | null,
  regNumber?: ModelStringInput | null,
  trustedPayer?: ModelBooleanInput | null,
  creditLimit?: ModelIntInput | null,
  billingAddress?: ModelStringInput | null,
  accountsEmail?: ModelStringInput | null,
  vatNumber?: ModelStringInput | null,
  taxReference?: ModelStringInput | null,
  vatExempt?: ModelBooleanInput | null,
  vatReverse?: ModelBooleanInput | null,
  cisDeductions?: ModelBooleanInput | null,
  cisName?: ModelStringInput | null,
  cisRate?: ModelStringInput | null,
  cisOrgType?: ModelStringInput | null,
  and?: Array< ModelCustomersFilterInput | null > | null,
  or?: Array< ModelCustomersFilterInput | null > | null,
  not?: ModelCustomersFilterInput | null,
};

export type ModelCustomersConnection = {
  __typename: "ModelCustomersConnection",
  items:  Array<Customers | null >,
  nextToken?: string | null,
  startedAt?: number | null,
};

export type ModelSubscriptionPendingFilterInput = {
  id?: ModelSubscriptionIDInput | null,
  purchaseOrder?: ModelSubscriptionBooleanInput | null,
  survey?: ModelSubscriptionBooleanInput | null,
  drawingsApproved?: ModelSubscriptionBooleanInput | null,
  drawings?: ModelSubscriptionBooleanInput | null,
  completed?: ModelSubscriptionBooleanInput | null,
  depositPaid?: ModelSubscriptionBooleanInput | null,
  orderPlaced?: ModelSubscriptionBooleanInput | null,
  shippingDetails?: ModelSubscriptionBooleanInput | null,
  invoices?: ModelSubscriptionBooleanInput | null,
  quotationDetails?: ModelSubscriptionBooleanInput | null,
  and?: Array< ModelSubscriptionPendingFilterInput | null > | null,
  or?: Array< ModelSubscriptionPendingFilterInput | null > | null,
};

export type ModelSubscriptionIDInput = {
  ne?: string | null,
  eq?: string | null,
  le?: string | null,
  lt?: string | null,
  ge?: string | null,
  gt?: string | null,
  contains?: string | null,
  notContains?: string | null,
  between?: Array< string | null > | null,
  beginsWith?: string | null,
  in?: Array< string | null > | null,
  notIn?: Array< string | null > | null,
};

export type ModelSubscriptionBooleanInput = {
  ne?: boolean | null,
  eq?: boolean | null,
};

export type ModelSubscriptionOrderInfFilterInput = {
  id?: ModelSubscriptionIDInput | null,
  itemName?: ModelSubscriptionStringInput | null,
  itemQuantity?: ModelSubscriptionIntInput | null,
  width?: ModelSubscriptionIntInput | null,
  drop?: ModelSubscriptionIntInput | null,
  cost?: ModelSubscriptionFloatInput | null,
  ordersID?: ModelSubscriptionIDInput | null,
  reference?: ModelSubscriptionStringInput | null,
  production?: ModelSubscriptionBooleanInput | null,
  extras?: ModelSubscriptionStringInput | null,
  productionSpecification?: ModelSubscriptionStringInput | null,
  and?: Array< ModelSubscriptionOrderInfFilterInput | null > | null,
  or?: Array< ModelSubscriptionOrderInfFilterInput | null > | null,
};

export type ModelSubscriptionStringInput = {
  ne?: string | null,
  eq?: string | null,
  le?: string | null,
  lt?: string | null,
  ge?: string | null,
  gt?: string | null,
  contains?: string | null,
  notContains?: string | null,
  between?: Array< string | null > | null,
  beginsWith?: string | null,
  in?: Array< string | null > | null,
  notIn?: Array< string | null > | null,
};

export type ModelSubscriptionIntInput = {
  ne?: number | null,
  eq?: number | null,
  le?: number | null,
  lt?: number | null,
  ge?: number | null,
  gt?: number | null,
  between?: Array< number | null > | null,
  in?: Array< number | null > | null,
  notIn?: Array< number | null > | null,
};

export type ModelSubscriptionFloatInput = {
  ne?: number | null,
  eq?: number | null,
  le?: number | null,
  lt?: number | null,
  ge?: number | null,
  gt?: number | null,
  between?: Array< number | null > | null,
  in?: Array< number | null > | null,
  notIn?: Array< number | null > | null,
};

export type ModelSubscriptionOrdersFilterInput = {
  id?: ModelSubscriptionIDInput | null,
  orderDate?: ModelSubscriptionStringInput | null,
  quotationNo?: ModelSubscriptionStringInput | null,
  projectName?: ModelSubscriptionStringInput | null,
  projectReference?: ModelSubscriptionStringInput | null,
  siteContactManager?: ModelSubscriptionStringInput | null,
  siteContactSupervisor?: ModelSubscriptionStringInput | null,
  status?: ModelSubscriptionStringInput | null,
  orderValue?: ModelSubscriptionFloatInput | null,
  siteAddress?: ModelSubscriptionStringInput | null,
  customersID?: ModelSubscriptionIDInput | null,
  lastUpdatedBy?: ModelSubscriptionStringInput | null,
  sfclTerms?: ModelSubscriptionStringInput | null,
  sfclCreditScore?: ModelSubscriptionStringInput | null,
  sfclRecommended?: ModelSubscriptionStringInput | null,
  sfclInsured?: ModelSubscriptionBooleanInput | null,
  supply?: ModelSubscriptionStringInput | null,
  customerCollection?: ModelSubscriptionBooleanInput | null,
  deliveryCharge?: ModelSubscriptionStringInput | null,
  estimatedCollectionDelivery?: ModelSubscriptionStringInput | null,
  estimateProjectCompletion?: ModelSubscriptionStringInput | null,
  sfclDelivered?: ModelSubscriptionStringInput | null,
  siteContactManagerNumber?: ModelSubscriptionStringInput | null,
  siteContactSupervisorNumber?: ModelSubscriptionStringInput | null,
  siteWorkingHours?: ModelSubscriptionStringInput | null,
  and?: Array< ModelSubscriptionOrdersFilterInput | null > | null,
  or?: Array< ModelSubscriptionOrdersFilterInput | null > | null,
};

export type ModelSubscriptionCustomersFilterInput = {
  id?: ModelSubscriptionIDInput | null,
  customer?: ModelSubscriptionStringInput | null,
  businessName?: ModelSubscriptionStringInput | null,
  email?: ModelSubscriptionStringInput | null,
  contactNum?: ModelSubscriptionStringInput | null,
  accountsContact?: ModelSubscriptionStringInput | null,
  regNumber?: ModelSubscriptionStringInput | null,
  trustedPayer?: ModelSubscriptionBooleanInput | null,
  creditLimit?: ModelSubscriptionIntInput | null,
  billingAddress?: ModelSubscriptionStringInput | null,
  accountsEmail?: ModelSubscriptionStringInput | null,
  vatNumber?: ModelSubscriptionStringInput | null,
  taxReference?: ModelSubscriptionStringInput | null,
  vatExempt?: ModelSubscriptionBooleanInput | null,
  vatReverse?: ModelSubscriptionBooleanInput | null,
  cisDeductions?: ModelSubscriptionBooleanInput | null,
  cisName?: ModelSubscriptionStringInput | null,
  cisRate?: ModelSubscriptionStringInput | null,
  cisOrgType?: ModelSubscriptionStringInput | null,
  and?: Array< ModelSubscriptionCustomersFilterInput | null > | null,
  or?: Array< ModelSubscriptionCustomersFilterInput | null > | null,
};

export type CreatePendingMutationVariables = {
  input: CreatePendingInput,
  condition?: ModelPendingConditionInput | null,
};

export type CreatePendingMutation = {
  createPending?:  {
    __typename: "Pending",
    id: string,
    purchaseOrder?: boolean | null,
    survey?: boolean | null,
    drawingsApproved?: boolean | null,
    drawings?: boolean | null,
    completed?: boolean | null,
    depositPaid?: boolean | null,
    orderPlaced?: boolean | null,
    shippingDetails?: boolean | null,
    invoices?: boolean | null,
    quotationDetails?: boolean | null,
    createdAt: string,
    updatedAt: string,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
  } | null,
};

export type UpdatePendingMutationVariables = {
  input: UpdatePendingInput,
  condition?: ModelPendingConditionInput | null,
};

export type UpdatePendingMutation = {
  updatePending?:  {
    __typename: "Pending",
    id: string,
    purchaseOrder?: boolean | null,
    survey?: boolean | null,
    drawingsApproved?: boolean | null,
    drawings?: boolean | null,
    completed?: boolean | null,
    depositPaid?: boolean | null,
    orderPlaced?: boolean | null,
    shippingDetails?: boolean | null,
    invoices?: boolean | null,
    quotationDetails?: boolean | null,
    createdAt: string,
    updatedAt: string,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
  } | null,
};

export type DeletePendingMutationVariables = {
  input: DeletePendingInput,
  condition?: ModelPendingConditionInput | null,
};

export type DeletePendingMutation = {
  deletePending?:  {
    __typename: "Pending",
    id: string,
    purchaseOrder?: boolean | null,
    survey?: boolean | null,
    drawingsApproved?: boolean | null,
    drawings?: boolean | null,
    completed?: boolean | null,
    depositPaid?: boolean | null,
    orderPlaced?: boolean | null,
    shippingDetails?: boolean | null,
    invoices?: boolean | null,
    quotationDetails?: boolean | null,
    createdAt: string,
    updatedAt: string,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
  } | null,
};

export type CreateOrderInfMutationVariables = {
  input: CreateOrderInfInput,
  condition?: ModelOrderInfConditionInput | null,
};

export type CreateOrderInfMutation = {
  createOrderInf?:  {
    __typename: "OrderInf",
    id: string,
    itemName?: string | null,
    itemQuantity?: number | null,
    width?: number | null,
    drop?: number | null,
    cost?: number | null,
    ordersID: string,
    reference?: string | null,
    production?: boolean | null,
    extras?: Array< string | null > | null,
    productionSpecification?: string | null,
    createdAt: string,
    updatedAt: string,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
  } | null,
};

export type UpdateOrderInfMutationVariables = {
  input: UpdateOrderInfInput,
  condition?: ModelOrderInfConditionInput | null,
};

export type UpdateOrderInfMutation = {
  updateOrderInf?:  {
    __typename: "OrderInf",
    id: string,
    itemName?: string | null,
    itemQuantity?: number | null,
    width?: number | null,
    drop?: number | null,
    cost?: number | null,
    ordersID: string,
    reference?: string | null,
    production?: boolean | null,
    extras?: Array< string | null > | null,
    productionSpecification?: string | null,
    createdAt: string,
    updatedAt: string,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
  } | null,
};

export type DeleteOrderInfMutationVariables = {
  input: DeleteOrderInfInput,
  condition?: ModelOrderInfConditionInput | null,
};

export type DeleteOrderInfMutation = {
  deleteOrderInf?:  {
    __typename: "OrderInf",
    id: string,
    itemName?: string | null,
    itemQuantity?: number | null,
    width?: number | null,
    drop?: number | null,
    cost?: number | null,
    ordersID: string,
    reference?: string | null,
    production?: boolean | null,
    extras?: Array< string | null > | null,
    productionSpecification?: string | null,
    createdAt: string,
    updatedAt: string,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
  } | null,
};

export type CreateOrdersMutationVariables = {
  input: CreateOrdersInput,
  condition?: ModelOrdersConditionInput | null,
};

export type CreateOrdersMutation = {
  createOrders?:  {
    __typename: "Orders",
    id: string,
    orderDate?: string | null,
    quotationNo?: string | null,
    projectName?: string | null,
    projectReference?: string | null,
    siteContactManager?: string | null,
    siteContactSupervisor?: string | null,
    status?: Status | null,
    orderValue?: number | null,
    siteAddress?: string | null,
    customersID: string,
    OrderInfs?:  {
      __typename: "ModelOrderInfConnection",
      nextToken?: string | null,
      startedAt?: number | null,
    } | null,
    lastUpdatedBy: string,
    Pending?:  {
      __typename: "Pending",
      id: string,
      purchaseOrder?: boolean | null,
      survey?: boolean | null,
      drawingsApproved?: boolean | null,
      drawings?: boolean | null,
      completed?: boolean | null,
      depositPaid?: boolean | null,
      orderPlaced?: boolean | null,
      shippingDetails?: boolean | null,
      invoices?: boolean | null,
      quotationDetails?: boolean | null,
      createdAt: string,
      updatedAt: string,
      _version: number,
      _deleted?: boolean | null,
      _lastChangedAt: number,
    } | null,
    sfclTerms?: string | null,
    sfclCreditScore?: string | null,
    sfclRecommended?: string | null,
    sfclInsured?: boolean | null,
    supply?: string | null,
    customerCollection?: boolean | null,
    deliveryCharge?: string | null,
    estimatedCollectionDelivery?: string | null,
    estimateProjectCompletion?: string | null,
    sfclDelivered?: string | null,
    siteContactManagerNumber?: string | null,
    siteContactSupervisorNumber?: string | null,
    siteWorkingHours?: string | null,
    createdAt: string,
    updatedAt: string,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
    ordersPendingId?: string | null,
  } | null,
};

export type UpdateOrdersMutationVariables = {
  input: UpdateOrdersInput,
  condition?: ModelOrdersConditionInput | null,
};

export type UpdateOrdersMutation = {
  updateOrders?:  {
    __typename: "Orders",
    id: string,
    orderDate?: string | null,
    quotationNo?: string | null,
    projectName?: string | null,
    projectReference?: string | null,
    siteContactManager?: string | null,
    siteContactSupervisor?: string | null,
    status?: Status | null,
    orderValue?: number | null,
    siteAddress?: string | null,
    customersID: string,
    OrderInfs?:  {
      __typename: "ModelOrderInfConnection",
      nextToken?: string | null,
      startedAt?: number | null,
    } | null,
    lastUpdatedBy: string,
    Pending?:  {
      __typename: "Pending",
      id: string,
      purchaseOrder?: boolean | null,
      survey?: boolean | null,
      drawingsApproved?: boolean | null,
      drawings?: boolean | null,
      completed?: boolean | null,
      depositPaid?: boolean | null,
      orderPlaced?: boolean | null,
      shippingDetails?: boolean | null,
      invoices?: boolean | null,
      quotationDetails?: boolean | null,
      createdAt: string,
      updatedAt: string,
      _version: number,
      _deleted?: boolean | null,
      _lastChangedAt: number,
    } | null,
    sfclTerms?: string | null,
    sfclCreditScore?: string | null,
    sfclRecommended?: string | null,
    sfclInsured?: boolean | null,
    supply?: string | null,
    customerCollection?: boolean | null,
    deliveryCharge?: string | null,
    estimatedCollectionDelivery?: string | null,
    estimateProjectCompletion?: string | null,
    sfclDelivered?: string | null,
    siteContactManagerNumber?: string | null,
    siteContactSupervisorNumber?: string | null,
    siteWorkingHours?: string | null,
    createdAt: string,
    updatedAt: string,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
    ordersPendingId?: string | null,
  } | null,
};

export type DeleteOrdersMutationVariables = {
  input: DeleteOrdersInput,
  condition?: ModelOrdersConditionInput | null,
};

export type DeleteOrdersMutation = {
  deleteOrders?:  {
    __typename: "Orders",
    id: string,
    orderDate?: string | null,
    quotationNo?: string | null,
    projectName?: string | null,
    projectReference?: string | null,
    siteContactManager?: string | null,
    siteContactSupervisor?: string | null,
    status?: Status | null,
    orderValue?: number | null,
    siteAddress?: string | null,
    customersID: string,
    OrderInfs?:  {
      __typename: "ModelOrderInfConnection",
      nextToken?: string | null,
      startedAt?: number | null,
    } | null,
    lastUpdatedBy: string,
    Pending?:  {
      __typename: "Pending",
      id: string,
      purchaseOrder?: boolean | null,
      survey?: boolean | null,
      drawingsApproved?: boolean | null,
      drawings?: boolean | null,
      completed?: boolean | null,
      depositPaid?: boolean | null,
      orderPlaced?: boolean | null,
      shippingDetails?: boolean | null,
      invoices?: boolean | null,
      quotationDetails?: boolean | null,
      createdAt: string,
      updatedAt: string,
      _version: number,
      _deleted?: boolean | null,
      _lastChangedAt: number,
    } | null,
    sfclTerms?: string | null,
    sfclCreditScore?: string | null,
    sfclRecommended?: string | null,
    sfclInsured?: boolean | null,
    supply?: string | null,
    customerCollection?: boolean | null,
    deliveryCharge?: string | null,
    estimatedCollectionDelivery?: string | null,
    estimateProjectCompletion?: string | null,
    sfclDelivered?: string | null,
    siteContactManagerNumber?: string | null,
    siteContactSupervisorNumber?: string | null,
    siteWorkingHours?: string | null,
    createdAt: string,
    updatedAt: string,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
    ordersPendingId?: string | null,
  } | null,
};

export type CreateCustomersMutationVariables = {
  input: CreateCustomersInput,
  condition?: ModelCustomersConditionInput | null,
};

export type CreateCustomersMutation = {
  createCustomers?:  {
    __typename: "Customers",
    id: string,
    customer: string,
    businessName?: string | null,
    email?: string | null,
    contactNum?: string | null,
    accountsContact?: string | null,
    regNumber?: string | null,
    trustedPayer?: boolean | null,
    creditLimit?: number | null,
    Orders?:  {
      __typename: "ModelOrdersConnection",
      nextToken?: string | null,
      startedAt?: number | null,
    } | null,
    billingAddress?: string | null,
    accountsEmail?: string | null,
    vatNumber?: string | null,
    taxReference?: string | null,
    vatExempt?: boolean | null,
    vatReverse?: boolean | null,
    cisDeductions?: boolean | null,
    cisName?: string | null,
    cisRate?: string | null,
    cisOrgType?: string | null,
    createdAt: string,
    updatedAt: string,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
  } | null,
};

export type UpdateCustomersMutationVariables = {
  input: UpdateCustomersInput,
  condition?: ModelCustomersConditionInput | null,
};

export type UpdateCustomersMutation = {
  updateCustomers?:  {
    __typename: "Customers",
    id: string,
    customer: string,
    businessName?: string | null,
    email?: string | null,
    contactNum?: string | null,
    accountsContact?: string | null,
    regNumber?: string | null,
    trustedPayer?: boolean | null,
    creditLimit?: number | null,
    Orders?:  {
      __typename: "ModelOrdersConnection",
      nextToken?: string | null,
      startedAt?: number | null,
    } | null,
    billingAddress?: string | null,
    accountsEmail?: string | null,
    vatNumber?: string | null,
    taxReference?: string | null,
    vatExempt?: boolean | null,
    vatReverse?: boolean | null,
    cisDeductions?: boolean | null,
    cisName?: string | null,
    cisRate?: string | null,
    cisOrgType?: string | null,
    createdAt: string,
    updatedAt: string,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
  } | null,
};

export type DeleteCustomersMutationVariables = {
  input: DeleteCustomersInput,
  condition?: ModelCustomersConditionInput | null,
};

export type DeleteCustomersMutation = {
  deleteCustomers?:  {
    __typename: "Customers",
    id: string,
    customer: string,
    businessName?: string | null,
    email?: string | null,
    contactNum?: string | null,
    accountsContact?: string | null,
    regNumber?: string | null,
    trustedPayer?: boolean | null,
    creditLimit?: number | null,
    Orders?:  {
      __typename: "ModelOrdersConnection",
      nextToken?: string | null,
      startedAt?: number | null,
    } | null,
    billingAddress?: string | null,
    accountsEmail?: string | null,
    vatNumber?: string | null,
    taxReference?: string | null,
    vatExempt?: boolean | null,
    vatReverse?: boolean | null,
    cisDeductions?: boolean | null,
    cisName?: string | null,
    cisRate?: string | null,
    cisOrgType?: string | null,
    createdAt: string,
    updatedAt: string,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
  } | null,
};

export type GetPendingQueryVariables = {
  id: string,
};

export type GetPendingQuery = {
  getPending?:  {
    __typename: "Pending",
    id: string,
    purchaseOrder?: boolean | null,
    survey?: boolean | null,
    drawingsApproved?: boolean | null,
    drawings?: boolean | null,
    completed?: boolean | null,
    depositPaid?: boolean | null,
    orderPlaced?: boolean | null,
    shippingDetails?: boolean | null,
    invoices?: boolean | null,
    quotationDetails?: boolean | null,
    createdAt: string,
    updatedAt: string,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
  } | null,
};

export type ListPendingsQueryVariables = {
  filter?: ModelPendingFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ListPendingsQuery = {
  listPendings?:  {
    __typename: "ModelPendingConnection",
    items:  Array< {
      __typename: "Pending",
      id: string,
      purchaseOrder?: boolean | null,
      survey?: boolean | null,
      drawingsApproved?: boolean | null,
      drawings?: boolean | null,
      completed?: boolean | null,
      depositPaid?: boolean | null,
      orderPlaced?: boolean | null,
      shippingDetails?: boolean | null,
      invoices?: boolean | null,
      quotationDetails?: boolean | null,
      createdAt: string,
      updatedAt: string,
      _version: number,
      _deleted?: boolean | null,
      _lastChangedAt: number,
    } | null >,
    nextToken?: string | null,
    startedAt?: number | null,
  } | null,
};

export type SyncPendingsQueryVariables = {
  filter?: ModelPendingFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
  lastSync?: number | null,
};

export type SyncPendingsQuery = {
  syncPendings?:  {
    __typename: "ModelPendingConnection",
    items:  Array< {
      __typename: "Pending",
      id: string,
      purchaseOrder?: boolean | null,
      survey?: boolean | null,
      drawingsApproved?: boolean | null,
      drawings?: boolean | null,
      completed?: boolean | null,
      depositPaid?: boolean | null,
      orderPlaced?: boolean | null,
      shippingDetails?: boolean | null,
      invoices?: boolean | null,
      quotationDetails?: boolean | null,
      createdAt: string,
      updatedAt: string,
      _version: number,
      _deleted?: boolean | null,
      _lastChangedAt: number,
    } | null >,
    nextToken?: string | null,
    startedAt?: number | null,
  } | null,
};

export type GetOrderInfQueryVariables = {
  id: string,
};

export type GetOrderInfQuery = {
  getOrderInf?:  {
    __typename: "OrderInf",
    id: string,
    itemName?: string | null,
    itemQuantity?: number | null,
    width?: number | null,
    drop?: number | null,
    cost?: number | null,
    ordersID: string,
    reference?: string | null,
    production?: boolean | null,
    extras?: Array< string | null > | null,
    productionSpecification?: string | null,
    createdAt: string,
    updatedAt: string,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
  } | null,
};

export type ListOrderInfsQueryVariables = {
  filter?: ModelOrderInfFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ListOrderInfsQuery = {
  listOrderInfs?:  {
    __typename: "ModelOrderInfConnection",
    items:  Array< {
      __typename: "OrderInf",
      id: string,
      itemName?: string | null,
      itemQuantity?: number | null,
      width?: number | null,
      drop?: number | null,
      cost?: number | null,
      ordersID: string,
      reference?: string | null,
      production?: boolean | null,
      extras?: Array< string | null > | null,
      productionSpecification?: string | null,
      createdAt: string,
      updatedAt: string,
      _version: number,
      _deleted?: boolean | null,
      _lastChangedAt: number,
    } | null >,
    nextToken?: string | null,
    startedAt?: number | null,
  } | null,
};

export type SyncOrderInfsQueryVariables = {
  filter?: ModelOrderInfFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
  lastSync?: number | null,
};

export type SyncOrderInfsQuery = {
  syncOrderInfs?:  {
    __typename: "ModelOrderInfConnection",
    items:  Array< {
      __typename: "OrderInf",
      id: string,
      itemName?: string | null,
      itemQuantity?: number | null,
      width?: number | null,
      drop?: number | null,
      cost?: number | null,
      ordersID: string,
      reference?: string | null,
      production?: boolean | null,
      extras?: Array< string | null > | null,
      productionSpecification?: string | null,
      createdAt: string,
      updatedAt: string,
      _version: number,
      _deleted?: boolean | null,
      _lastChangedAt: number,
    } | null >,
    nextToken?: string | null,
    startedAt?: number | null,
  } | null,
};

export type OrderInfsByOrdersIDQueryVariables = {
  ordersID: string,
  sortDirection?: ModelSortDirection | null,
  filter?: ModelOrderInfFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type OrderInfsByOrdersIDQuery = {
  orderInfsByOrdersID?:  {
    __typename: "ModelOrderInfConnection",
    items:  Array< {
      __typename: "OrderInf",
      id: string,
      itemName?: string | null,
      itemQuantity?: number | null,
      width?: number | null,
      drop?: number | null,
      cost?: number | null,
      ordersID: string,
      reference?: string | null,
      production?: boolean | null,
      extras?: Array< string | null > | null,
      productionSpecification?: string | null,
      createdAt: string,
      updatedAt: string,
      _version: number,
      _deleted?: boolean | null,
      _lastChangedAt: number,
    } | null >,
    nextToken?: string | null,
    startedAt?: number | null,
  } | null,
};

export type GetOrdersQueryVariables = {
  id: string,
};

export type GetOrdersQuery = {
  getOrders?:  {
    __typename: "Orders",
    id: string,
    orderDate?: string | null,
    quotationNo?: string | null,
    projectName?: string | null,
    projectReference?: string | null,
    siteContactManager?: string | null,
    siteContactSupervisor?: string | null,
    status?: Status | null,
    orderValue?: number | null,
    siteAddress?: string | null,
    customersID: string,
    OrderInfs?:  {
      __typename: "ModelOrderInfConnection",
      nextToken?: string | null,
      startedAt?: number | null,
    } | null,
    lastUpdatedBy: string,
    Pending?:  {
      __typename: "Pending",
      id: string,
      purchaseOrder?: boolean | null,
      survey?: boolean | null,
      drawingsApproved?: boolean | null,
      drawings?: boolean | null,
      completed?: boolean | null,
      depositPaid?: boolean | null,
      orderPlaced?: boolean | null,
      shippingDetails?: boolean | null,
      invoices?: boolean | null,
      quotationDetails?: boolean | null,
      createdAt: string,
      updatedAt: string,
      _version: number,
      _deleted?: boolean | null,
      _lastChangedAt: number,
    } | null,
    sfclTerms?: string | null,
    sfclCreditScore?: string | null,
    sfclRecommended?: string | null,
    sfclInsured?: boolean | null,
    supply?: string | null,
    customerCollection?: boolean | null,
    deliveryCharge?: string | null,
    estimatedCollectionDelivery?: string | null,
    estimateProjectCompletion?: string | null,
    sfclDelivered?: string | null,
    siteContactManagerNumber?: string | null,
    siteContactSupervisorNumber?: string | null,
    siteWorkingHours?: string | null,
    createdAt: string,
    updatedAt: string,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
    ordersPendingId?: string | null,
  } | null,
};

export type ListOrdersQueryVariables = {
  filter?: ModelOrdersFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ListOrdersQuery = {
  listOrders?:  {
    __typename: "ModelOrdersConnection",
    items:  Array< {
      __typename: "Orders",
      id: string,
      orderDate?: string | null,
      quotationNo?: string | null,
      projectName?: string | null,
      projectReference?: string | null,
      siteContactManager?: string | null,
      siteContactSupervisor?: string | null,
      status?: Status | null,
      orderValue?: number | null,
      siteAddress?: string | null,
      customersID: string,
      lastUpdatedBy: string,
      sfclTerms?: string | null,
      sfclCreditScore?: string | null,
      sfclRecommended?: string | null,
      sfclInsured?: boolean | null,
      supply?: string | null,
      customerCollection?: boolean | null,
      deliveryCharge?: string | null,
      estimatedCollectionDelivery?: string | null,
      estimateProjectCompletion?: string | null,
      sfclDelivered?: string | null,
      siteContactManagerNumber?: string | null,
      siteContactSupervisorNumber?: string | null,
      siteWorkingHours?: string | null,
      createdAt: string,
      updatedAt: string,
      _version: number,
      _deleted?: boolean | null,
      _lastChangedAt: number,
      ordersPendingId?: string | null,
    } | null >,
    nextToken?: string | null,
    startedAt?: number | null,
  } | null,
};

export type SyncOrdersQueryVariables = {
  filter?: ModelOrdersFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
  lastSync?: number | null,
};

export type SyncOrdersQuery = {
  syncOrders?:  {
    __typename: "ModelOrdersConnection",
    items:  Array< {
      __typename: "Orders",
      id: string,
      orderDate?: string | null,
      quotationNo?: string | null,
      projectName?: string | null,
      projectReference?: string | null,
      siteContactManager?: string | null,
      siteContactSupervisor?: string | null,
      status?: Status | null,
      orderValue?: number | null,
      siteAddress?: string | null,
      customersID: string,
      lastUpdatedBy: string,
      sfclTerms?: string | null,
      sfclCreditScore?: string | null,
      sfclRecommended?: string | null,
      sfclInsured?: boolean | null,
      supply?: string | null,
      customerCollection?: boolean | null,
      deliveryCharge?: string | null,
      estimatedCollectionDelivery?: string | null,
      estimateProjectCompletion?: string | null,
      sfclDelivered?: string | null,
      siteContactManagerNumber?: string | null,
      siteContactSupervisorNumber?: string | null,
      siteWorkingHours?: string | null,
      createdAt: string,
      updatedAt: string,
      _version: number,
      _deleted?: boolean | null,
      _lastChangedAt: number,
      ordersPendingId?: string | null,
    } | null >,
    nextToken?: string | null,
    startedAt?: number | null,
  } | null,
};

export type OrdersByCustomersIDQueryVariables = {
  customersID: string,
  sortDirection?: ModelSortDirection | null,
  filter?: ModelOrdersFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type OrdersByCustomersIDQuery = {
  ordersByCustomersID?:  {
    __typename: "ModelOrdersConnection",
    items:  Array< {
      __typename: "Orders",
      id: string,
      orderDate?: string | null,
      quotationNo?: string | null,
      projectName?: string | null,
      projectReference?: string | null,
      siteContactManager?: string | null,
      siteContactSupervisor?: string | null,
      status?: Status | null,
      orderValue?: number | null,
      siteAddress?: string | null,
      customersID: string,
      lastUpdatedBy: string,
      sfclTerms?: string | null,
      sfclCreditScore?: string | null,
      sfclRecommended?: string | null,
      sfclInsured?: boolean | null,
      supply?: string | null,
      customerCollection?: boolean | null,
      deliveryCharge?: string | null,
      estimatedCollectionDelivery?: string | null,
      estimateProjectCompletion?: string | null,
      sfclDelivered?: string | null,
      siteContactManagerNumber?: string | null,
      siteContactSupervisorNumber?: string | null,
      siteWorkingHours?: string | null,
      createdAt: string,
      updatedAt: string,
      _version: number,
      _deleted?: boolean | null,
      _lastChangedAt: number,
      ordersPendingId?: string | null,
    } | null >,
    nextToken?: string | null,
    startedAt?: number | null,
  } | null,
};

export type GetCustomersQueryVariables = {
  id: string,
};

export type GetCustomersQuery = {
  getCustomers?:  {
    __typename: "Customers",
    id: string,
    customer: string,
    businessName?: string | null,
    email?: string | null,
    contactNum?: string | null,
    accountsContact?: string | null,
    regNumber?: string | null,
    trustedPayer?: boolean | null,
    creditLimit?: number | null,
    Orders?:  {
      __typename: "ModelOrdersConnection",
      nextToken?: string | null,
      startedAt?: number | null,
    } | null,
    billingAddress?: string | null,
    accountsEmail?: string | null,
    vatNumber?: string | null,
    taxReference?: string | null,
    vatExempt?: boolean | null,
    vatReverse?: boolean | null,
    cisDeductions?: boolean | null,
    cisName?: string | null,
    cisRate?: string | null,
    cisOrgType?: string | null,
    createdAt: string,
    updatedAt: string,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
  } | null,
};

export type ListCustomersQueryVariables = {
  filter?: ModelCustomersFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ListCustomersQuery = {
  listCustomers?:  {
    __typename: "ModelCustomersConnection",
    items:  Array< {
      __typename: "Customers",
      id: string,
      customer: string,
      businessName?: string | null,
      email?: string | null,
      contactNum?: string | null,
      accountsContact?: string | null,
      regNumber?: string | null,
      trustedPayer?: boolean | null,
      creditLimit?: number | null,
      billingAddress?: string | null,
      accountsEmail?: string | null,
      vatNumber?: string | null,
      taxReference?: string | null,
      vatExempt?: boolean | null,
      vatReverse?: boolean | null,
      cisDeductions?: boolean | null,
      cisName?: string | null,
      cisRate?: string | null,
      cisOrgType?: string | null,
      createdAt: string,
      updatedAt: string,
      _version: number,
      _deleted?: boolean | null,
      _lastChangedAt: number,
    } | null >,
    nextToken?: string | null,
    startedAt?: number | null,
  } | null,
};

export type SyncCustomersQueryVariables = {
  filter?: ModelCustomersFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
  lastSync?: number | null,
};

export type SyncCustomersQuery = {
  syncCustomers?:  {
    __typename: "ModelCustomersConnection",
    items:  Array< {
      __typename: "Customers",
      id: string,
      customer: string,
      businessName?: string | null,
      email?: string | null,
      contactNum?: string | null,
      accountsContact?: string | null,
      regNumber?: string | null,
      trustedPayer?: boolean | null,
      creditLimit?: number | null,
      billingAddress?: string | null,
      accountsEmail?: string | null,
      vatNumber?: string | null,
      taxReference?: string | null,
      vatExempt?: boolean | null,
      vatReverse?: boolean | null,
      cisDeductions?: boolean | null,
      cisName?: string | null,
      cisRate?: string | null,
      cisOrgType?: string | null,
      createdAt: string,
      updatedAt: string,
      _version: number,
      _deleted?: boolean | null,
      _lastChangedAt: number,
    } | null >,
    nextToken?: string | null,
    startedAt?: number | null,
  } | null,
};

export type OnCreatePendingSubscriptionVariables = {
  filter?: ModelSubscriptionPendingFilterInput | null,
};

export type OnCreatePendingSubscription = {
  onCreatePending?:  {
    __typename: "Pending",
    id: string,
    purchaseOrder?: boolean | null,
    survey?: boolean | null,
    drawingsApproved?: boolean | null,
    drawings?: boolean | null,
    completed?: boolean | null,
    depositPaid?: boolean | null,
    orderPlaced?: boolean | null,
    shippingDetails?: boolean | null,
    invoices?: boolean | null,
    quotationDetails?: boolean | null,
    createdAt: string,
    updatedAt: string,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
  } | null,
};

export type OnUpdatePendingSubscriptionVariables = {
  filter?: ModelSubscriptionPendingFilterInput | null,
};

export type OnUpdatePendingSubscription = {
  onUpdatePending?:  {
    __typename: "Pending",
    id: string,
    purchaseOrder?: boolean | null,
    survey?: boolean | null,
    drawingsApproved?: boolean | null,
    drawings?: boolean | null,
    completed?: boolean | null,
    depositPaid?: boolean | null,
    orderPlaced?: boolean | null,
    shippingDetails?: boolean | null,
    invoices?: boolean | null,
    quotationDetails?: boolean | null,
    createdAt: string,
    updatedAt: string,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
  } | null,
};

export type OnDeletePendingSubscriptionVariables = {
  filter?: ModelSubscriptionPendingFilterInput | null,
};

export type OnDeletePendingSubscription = {
  onDeletePending?:  {
    __typename: "Pending",
    id: string,
    purchaseOrder?: boolean | null,
    survey?: boolean | null,
    drawingsApproved?: boolean | null,
    drawings?: boolean | null,
    completed?: boolean | null,
    depositPaid?: boolean | null,
    orderPlaced?: boolean | null,
    shippingDetails?: boolean | null,
    invoices?: boolean | null,
    quotationDetails?: boolean | null,
    createdAt: string,
    updatedAt: string,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
  } | null,
};

export type OnCreateOrderInfSubscriptionVariables = {
  filter?: ModelSubscriptionOrderInfFilterInput | null,
};

export type OnCreateOrderInfSubscription = {
  onCreateOrderInf?:  {
    __typename: "OrderInf",
    id: string,
    itemName?: string | null,
    itemQuantity?: number | null,
    width?: number | null,
    drop?: number | null,
    cost?: number | null,
    ordersID: string,
    reference?: string | null,
    production?: boolean | null,
    extras?: Array< string | null > | null,
    productionSpecification?: string | null,
    createdAt: string,
    updatedAt: string,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
  } | null,
};

export type OnUpdateOrderInfSubscriptionVariables = {
  filter?: ModelSubscriptionOrderInfFilterInput | null,
};

export type OnUpdateOrderInfSubscription = {
  onUpdateOrderInf?:  {
    __typename: "OrderInf",
    id: string,
    itemName?: string | null,
    itemQuantity?: number | null,
    width?: number | null,
    drop?: number | null,
    cost?: number | null,
    ordersID: string,
    reference?: string | null,
    production?: boolean | null,
    extras?: Array< string | null > | null,
    productionSpecification?: string | null,
    createdAt: string,
    updatedAt: string,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
  } | null,
};

export type OnDeleteOrderInfSubscriptionVariables = {
  filter?: ModelSubscriptionOrderInfFilterInput | null,
};

export type OnDeleteOrderInfSubscription = {
  onDeleteOrderInf?:  {
    __typename: "OrderInf",
    id: string,
    itemName?: string | null,
    itemQuantity?: number | null,
    width?: number | null,
    drop?: number | null,
    cost?: number | null,
    ordersID: string,
    reference?: string | null,
    production?: boolean | null,
    extras?: Array< string | null > | null,
    productionSpecification?: string | null,
    createdAt: string,
    updatedAt: string,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
  } | null,
};

export type OnCreateOrdersSubscriptionVariables = {
  filter?: ModelSubscriptionOrdersFilterInput | null,
};

export type OnCreateOrdersSubscription = {
  onCreateOrders?:  {
    __typename: "Orders",
    id: string,
    orderDate?: string | null,
    quotationNo?: string | null,
    projectName?: string | null,
    projectReference?: string | null,
    siteContactManager?: string | null,
    siteContactSupervisor?: string | null,
    status?: Status | null,
    orderValue?: number | null,
    siteAddress?: string | null,
    customersID: string,
    OrderInfs?:  {
      __typename: "ModelOrderInfConnection",
      nextToken?: string | null,
      startedAt?: number | null,
    } | null,
    lastUpdatedBy: string,
    Pending?:  {
      __typename: "Pending",
      id: string,
      purchaseOrder?: boolean | null,
      survey?: boolean | null,
      drawingsApproved?: boolean | null,
      drawings?: boolean | null,
      completed?: boolean | null,
      depositPaid?: boolean | null,
      orderPlaced?: boolean | null,
      shippingDetails?: boolean | null,
      invoices?: boolean | null,
      quotationDetails?: boolean | null,
      createdAt: string,
      updatedAt: string,
      _version: number,
      _deleted?: boolean | null,
      _lastChangedAt: number,
    } | null,
    sfclTerms?: string | null,
    sfclCreditScore?: string | null,
    sfclRecommended?: string | null,
    sfclInsured?: boolean | null,
    supply?: string | null,
    customerCollection?: boolean | null,
    deliveryCharge?: string | null,
    estimatedCollectionDelivery?: string | null,
    estimateProjectCompletion?: string | null,
    sfclDelivered?: string | null,
    siteContactManagerNumber?: string | null,
    siteContactSupervisorNumber?: string | null,
    siteWorkingHours?: string | null,
    createdAt: string,
    updatedAt: string,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
    ordersPendingId?: string | null,
  } | null,
};

export type OnUpdateOrdersSubscriptionVariables = {
  filter?: ModelSubscriptionOrdersFilterInput | null,
};

export type OnUpdateOrdersSubscription = {
  onUpdateOrders?:  {
    __typename: "Orders",
    id: string,
    orderDate?: string | null,
    quotationNo?: string | null,
    projectName?: string | null,
    projectReference?: string | null,
    siteContactManager?: string | null,
    siteContactSupervisor?: string | null,
    status?: Status | null,
    orderValue?: number | null,
    siteAddress?: string | null,
    customersID: string,
    OrderInfs?:  {
      __typename: "ModelOrderInfConnection",
      nextToken?: string | null,
      startedAt?: number | null,
    } | null,
    lastUpdatedBy: string,
    Pending?:  {
      __typename: "Pending",
      id: string,
      purchaseOrder?: boolean | null,
      survey?: boolean | null,
      drawingsApproved?: boolean | null,
      drawings?: boolean | null,
      completed?: boolean | null,
      depositPaid?: boolean | null,
      orderPlaced?: boolean | null,
      shippingDetails?: boolean | null,
      invoices?: boolean | null,
      quotationDetails?: boolean | null,
      createdAt: string,
      updatedAt: string,
      _version: number,
      _deleted?: boolean | null,
      _lastChangedAt: number,
    } | null,
    sfclTerms?: string | null,
    sfclCreditScore?: string | null,
    sfclRecommended?: string | null,
    sfclInsured?: boolean | null,
    supply?: string | null,
    customerCollection?: boolean | null,
    deliveryCharge?: string | null,
    estimatedCollectionDelivery?: string | null,
    estimateProjectCompletion?: string | null,
    sfclDelivered?: string | null,
    siteContactManagerNumber?: string | null,
    siteContactSupervisorNumber?: string | null,
    siteWorkingHours?: string | null,
    createdAt: string,
    updatedAt: string,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
    ordersPendingId?: string | null,
  } | null,
};

export type OnDeleteOrdersSubscriptionVariables = {
  filter?: ModelSubscriptionOrdersFilterInput | null,
};

export type OnDeleteOrdersSubscription = {
  onDeleteOrders?:  {
    __typename: "Orders",
    id: string,
    orderDate?: string | null,
    quotationNo?: string | null,
    projectName?: string | null,
    projectReference?: string | null,
    siteContactManager?: string | null,
    siteContactSupervisor?: string | null,
    status?: Status | null,
    orderValue?: number | null,
    siteAddress?: string | null,
    customersID: string,
    OrderInfs?:  {
      __typename: "ModelOrderInfConnection",
      nextToken?: string | null,
      startedAt?: number | null,
    } | null,
    lastUpdatedBy: string,
    Pending?:  {
      __typename: "Pending",
      id: string,
      purchaseOrder?: boolean | null,
      survey?: boolean | null,
      drawingsApproved?: boolean | null,
      drawings?: boolean | null,
      completed?: boolean | null,
      depositPaid?: boolean | null,
      orderPlaced?: boolean | null,
      shippingDetails?: boolean | null,
      invoices?: boolean | null,
      quotationDetails?: boolean | null,
      createdAt: string,
      updatedAt: string,
      _version: number,
      _deleted?: boolean | null,
      _lastChangedAt: number,
    } | null,
    sfclTerms?: string | null,
    sfclCreditScore?: string | null,
    sfclRecommended?: string | null,
    sfclInsured?: boolean | null,
    supply?: string | null,
    customerCollection?: boolean | null,
    deliveryCharge?: string | null,
    estimatedCollectionDelivery?: string | null,
    estimateProjectCompletion?: string | null,
    sfclDelivered?: string | null,
    siteContactManagerNumber?: string | null,
    siteContactSupervisorNumber?: string | null,
    siteWorkingHours?: string | null,
    createdAt: string,
    updatedAt: string,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
    ordersPendingId?: string | null,
  } | null,
};

export type OnCreateCustomersSubscriptionVariables = {
  filter?: ModelSubscriptionCustomersFilterInput | null,
};

export type OnCreateCustomersSubscription = {
  onCreateCustomers?:  {
    __typename: "Customers",
    id: string,
    customer: string,
    businessName?: string | null,
    email?: string | null,
    contactNum?: string | null,
    accountsContact?: string | null,
    regNumber?: string | null,
    trustedPayer?: boolean | null,
    creditLimit?: number | null,
    Orders?:  {
      __typename: "ModelOrdersConnection",
      nextToken?: string | null,
      startedAt?: number | null,
    } | null,
    billingAddress?: string | null,
    accountsEmail?: string | null,
    vatNumber?: string | null,
    taxReference?: string | null,
    vatExempt?: boolean | null,
    vatReverse?: boolean | null,
    cisDeductions?: boolean | null,
    cisName?: string | null,
    cisRate?: string | null,
    cisOrgType?: string | null,
    createdAt: string,
    updatedAt: string,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
  } | null,
};

export type OnUpdateCustomersSubscriptionVariables = {
  filter?: ModelSubscriptionCustomersFilterInput | null,
};

export type OnUpdateCustomersSubscription = {
  onUpdateCustomers?:  {
    __typename: "Customers",
    id: string,
    customer: string,
    businessName?: string | null,
    email?: string | null,
    contactNum?: string | null,
    accountsContact?: string | null,
    regNumber?: string | null,
    trustedPayer?: boolean | null,
    creditLimit?: number | null,
    Orders?:  {
      __typename: "ModelOrdersConnection",
      nextToken?: string | null,
      startedAt?: number | null,
    } | null,
    billingAddress?: string | null,
    accountsEmail?: string | null,
    vatNumber?: string | null,
    taxReference?: string | null,
    vatExempt?: boolean | null,
    vatReverse?: boolean | null,
    cisDeductions?: boolean | null,
    cisName?: string | null,
    cisRate?: string | null,
    cisOrgType?: string | null,
    createdAt: string,
    updatedAt: string,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
  } | null,
};

export type OnDeleteCustomersSubscriptionVariables = {
  filter?: ModelSubscriptionCustomersFilterInput | null,
};

export type OnDeleteCustomersSubscription = {
  onDeleteCustomers?:  {
    __typename: "Customers",
    id: string,
    customer: string,
    businessName?: string | null,
    email?: string | null,
    contactNum?: string | null,
    accountsContact?: string | null,
    regNumber?: string | null,
    trustedPayer?: boolean | null,
    creditLimit?: number | null,
    Orders?:  {
      __typename: "ModelOrdersConnection",
      nextToken?: string | null,
      startedAt?: number | null,
    } | null,
    billingAddress?: string | null,
    accountsEmail?: string | null,
    vatNumber?: string | null,
    taxReference?: string | null,
    vatExempt?: boolean | null,
    vatReverse?: boolean | null,
    cisDeductions?: boolean | null,
    cisName?: string | null,
    cisRate?: string | null,
    cisOrgType?: string | null,
    createdAt: string,
    updatedAt: string,
    _version: number,
    _deleted?: boolean | null,
    _lastChangedAt: number,
  } | null,
};
